name: CI Workflow
on: [push, pull_request]

jobs:
  client-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PortAudio
        run: sudo apt install -y portaudio19-dev

      - name: Install Python Dependencies
        run: pip install -r client/requirements.txt

      - name: Run Tests
        run: pytest client/ --cov=client/

      - name: Run Linter
        run: pylint client/src

  server-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t server .

      - name: Run Tests and Coverage in Docker
        run: docker run --rm server pytest server/ --cov=server/

      - name: Run Linter in Docker
        run: docker run --rm server pylint server/src